### ISSUE TITLE
Maintenance Application Code

### ISSUE THREAD

**Issue by GrahamDrive** [UMSATS/cdh-tsat#19]
**Background:** The satellite’s application code accomplishes the functionality of our flight mission, to fulfill our payload experiment. However, we need additional code beyond this, to ensure that the satellite is able to operate nominally over our mission lifetime. We will define this extra code as “maintenance code”.

**Maintenance Code Example:** During orbit, a section of the internal flash storage may become corrupted due to radiation. We can run a CRC check to determine if corruption has occurred. CDH will routinely perform this CRC check to evaluate the health of the satellite. The software which implements this routine CRC check is an example of “maintenance code”. This piece of software doesn’t explicitly implement the mission’s payload functionality. However, the code is just as essential, as it helps the satellite operate nominally.

**Task:**
1. Research cubesat flight software to determine what types of maintenance code our CDH software should implement. I would recommend looking at any open-source flight software of other cubesats, which have successfully launched and made it into orbit. There are likely also articles published online about flight software architecture for cubesats.

2. Document the proposed maintenance code which you think we should implement into our flight software. (Before doing any thorough documentation, feel free to reach out to me to discuss the code, to see if we’ll want to implement it. -Daigh)

3. Create a sample STM32 project for your NUCLEO board, which provides a demo for this maintenance code. Don’t worry about including all of the satellite application code in this project; just a simple program which demonstrates the maintenance code’s functionality is perfect.

4. After we review your sample project, we’ll work together to implement your code into CDH’s flight software.

**Comment by whatdoes3plus1equalsto** [comment]
pasting current found open source cubesat project:

UW Orbital
https://github.com/UWOrbital/OBC-firmware

UPSat
https://gitlab.com/librespacefoundation/upsat/upsat-obc-software

PyCubed
https://github.com/pycubed

**Comment by GrahamDrive** [comment]
Are any of these projects using STM?

**Comment by whatdoes3plus1equalsto** [comment]
> Are any of these projects using STM?

Unfortunately, none of these projects using STM, do you want to find some projects that are developed with STM?

**Comment by GrahamDrive** [comment]
No, just seeing what type of software these projects are implementing should be good enough. I was curious if any were STM.
